[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://ai-content-creator-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_GOOGLE_CLIENT_ID"
