[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true

[[redirects]]
  from = "/api/transcribe"
  to = "/.netlify/functions/transcribe"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/google/config"
  to = "/.netlify/functions/google-config"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_GOOGLE_CLIENT_ID"
